### ISSUE TITLE
can't install on ubuntu (/usr/bin/python)

### ISSUE THREAD

**Issue by tdcwilliams** [nansencenter/py-thesaurus-interface#13]
When I do the command:
pip install https://github.com/nansencenter/py-thesaurus-interface/archive/master.tar.gz

I get the error:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-t97wYu-build/setup.py", line 84, in <module>
        cmdclass = {'install_scripts': update_vocabularies}
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-12gS2d/xdg-2.0.0/setup.py", line 19, in <module>
        REQS = ['PyYAML', 'requests', 'xdg;platform_system!="Windows"']
      File "/tmp/easy_install-12gS2d/xdg-2.0.0/setup.py", line 12, in read_long_description
        from setuptools import setup, find_packages
    AttributeError: 'PosixPath' object has no attribute 'read_text'

**Comment by tdcwilliams** [comment]
this is python 2.7 by the way. I just tried with python3.5 and pip3 install ... worked. Is nansat also only working for python3 now?

**Comment by aleksandervines** [comment]
This is an issue with XDG 2.0 not supporting python 2 any more. You have to use xdg 1.0.5




----------------



Aleksander Vines

Programmer | IT, Scientific Data Management
+47 465 05 891 | aleksander.vines@nersc.no


Nansen Environmental and Remote Sensing Center

**Comment by tdcwilliams** [comment]
Thanks @aleksandervines - is there a way to do this with apt?

**Comment by aleksandervines** [comment]
Try this with pip:
`pip install https://github.com/srstevenson/xdg/archive/1.0.5.tar.gz`

**Comment by tdcwilliams** [comment]
Now I have a different error (version conflict) (pip install xdg 1.0.5 worked, but the pythesint install didn't):

 Installed /tmp/pip-keAXut-build/.eggs/urllib3-1.22-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-keAXut-build/setup.py", line 84, in <module>
        cmdclass = {'install_scripts': update_vocabularies}
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1085, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 695, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (idna 2.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('idna<2.7,>=2.5'))

**Comment by aleksandervines** [comment]
you need idna to match the string 'idna<2.7,>=2.5' to install the requests module it seems.

You seem to have idna 2.0, which version is specifically required by some other module you have installed.

I would always recommend using virtual environments of some sort when working with Python, package dependencies and version issues like this seems to quite often cause lots of issues.

**Comment by tdcwilliams** [comment]
@aleksandervines  - are you sure the original problem was not just a pathlib function that only exists for python3?

**Comment by aleksandervines** [comment]
Well, yes, I think that was the problem. But this pathlib was found when it tried to install xdg 2.0.0, which only supports python 3. If my interpretation of the stacktrace is correct.

**Comment by akorosov** [comment]
@aleksandervines , the issue with XDG persists on travis for Python 2.7. As a results build status - failed. Is there a way not to use XDG for python 2.7?

**Comment by aleksandervines** [comment]
You have to use a version of xdg that supports python 2.7. e.g. 1.0.5

**Comment by tdcwilliams** [comment]
how hard would it be to get nansat to work with python3?

**Comment by aleksandervines** [comment]
@tdcwilliams According to Artem it will be fairly simple. It is in our work-plan for the next 2 weeks. It does depend on us doing some large refactoring of Nansat first though.

**Comment by aleksandervines** [comment]
pythesint on pip has been updated, and should work on all platforms and both python 2.7 and 3.6

`pip install pythesint`

**Comment by tdcwilliams** [comment]
thanks @aleksandervines - it installed and "import nansat" works on py2.7 after running setup.py

**Comment by tdcwilliams** [comment]
no prob; btw "nosetests nansat" also works
