### ISSUE TITLE
Cannot import project keyword at python 3

### ISSUE THREAD

**Issue by korvinos** [nansencenter/py-thesaurus-interface#20]
I have got a problem with getting a **project** keywords from `pythesint` with python 3.6 (nansat VM). It works fine with py2 as well as with any other keywords (platforms, instruments) with py3.

```python
>>> import pythesint as pti
>>> pti.get_gcmd_project('GHRSST')

Traceback (most recent call last):
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-29c8ed8ce8a4>", line 1, in <module>
    pti.get_gcmd_project('GHRSST')
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/site-packages/pythesint/vocabulary.py", line 45, in find_keyword
    for d in self.get_list():
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/site-packages/pythesint/json_vocabulary.py", line 17, in get_list
    return self.sort_list(json.load(open(self.get_filepath())))
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vagrant/anaconda/envs/py3nansat/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by akorosov** [comment]
Try updating. I think that's not related to the version of python but to changed URLs of NASA gcmd. We recently released a new version.

**Comment by korvinos** [comment]
This helped, thanks! 
```python
pti.update_all_vocabularies()
```
