### ISSUE TITLE
python setup.py test does not work

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/py-thesaurus-interface#9]
```
File "/home/vagrant/miniconda/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_pythesint'
```
This is done in the develop vm. It is strange that the tests are passing on travis, though...

**Comment by mortenwh** [comment]
Also the following command fails:
```
python -m unittest pythesint.tests.test_vocabulary
Traceback (most recent call last):
  File "/home/vagrant/miniconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/vagrant/miniconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vagrant/miniconda/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/home/vagrant/miniconda/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/vagrant/miniconda/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/home/vagrant/miniconda/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/home/vagrant/miniconda/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/vagrant/miniconda/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_vocabulary'
```

**Comment by mortenwh** [comment]
From @akorosov, this should work:
```
pip install mock
nosetests pythesint
```
And it does. So, after installing mock, also ```python setup.py test```works as expected :) I've added mock to the nersc-vagrant provisioning.
